# Generated by Django 4.0.5 on 2022-11-18 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_bio', models.TextField(max_length=500)),
                ('zip_code', models.CharField(max_length=20)),
                ('skills', models.CharField(max_length=200)),
                ('github', models.CharField(blank=True, max_length=50)),
                ('years_of_experience', models.IntegerField()),
                ('education', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
