# Generated by Django 4.0.5 on 2022-11-18 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_recruiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_recruiter',
        ),
    ]
