# Generated by Django 4.0.5 on 2022-11-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
