# Generated by Django 4.0.5 on 2022-11-18 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_is_recruiter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
