# Generated by Django 4.0.5 on 2022-11-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_posts_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('Inactive', 'Inactive')], max_length=20),
        ),
    ]
