# Generated by Django 4.0.5 on 2022-11-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='interested_candidates',
            field=models.ManyToManyField(blank=True, to='users.candidate'),
        ),
    ]
